// This file is automatically generated, but we've adjusted it to use
// the manualSupabaseClient wrapper to avoid env injection issues.
// If this file is regenerated in the future and you see `supabaseUrl is required`
// again, you can safely re-apply this small wrapper.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { manualSupabaseClient } from "./manualClient";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Re-export the manual client using the expected name and type
export const supabase: SupabaseClient<Database> = manualSupabaseClient;
